### ISSUE TITLE
File to import not found or unreadable: artic_admin/base

### ISSUE THREAD

**Issue by lsarni** [cle61/arctic_admin#15]
I followed the `README`  but I'm getting this error:
```console
File to import not found or unreadable: artic_admin/base.
Load paths:
  /Users/lucia/Documents/fro/app/assets/config
  /Users/lucia/Documents/fro/app/assets/images
  /Users/lucia/Documents/fro/app/assets/javascripts
  /Users/lucia/Documents/fro/app/assets/stylesheets
  /Users/lucia/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/arctic_admin-1.3.0/app/assets/fonts
  /Users/lucia/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/arctic_admin-1.3.0/app/assets/javascripts
  /Users/lucia/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/arctic_admin-1.3.0/app/assets/stylesheets
```
I checked and the file `base.scss` is on the gem folder as expected.

This is my `active_admin.scss`:
```scss
// SASS variable overrides must be declared before loading up Active Admin's styles.
//
// To view the variables that Active Admin provides, take a look at
// `app/assets/stylesheets/active_admin/mixins/_variables.scss` in the
// Active Admin source.
//
// For example, to change the sidebar width:
// $sidebar-width: 242px;

// Active Admin's got SASS!
@import "active_admin/mixins";
@import "artic_admin/base";

// Overriding any non-variable SASS must be done after the fact.
// For example, to change the default status-tag color:
//
//   .status_tag { background: #6090DB; }

```
